# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SocketTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SocketTest
  pod 'Socket.IO-Client-Swift', '~> 8.3.3' # Or latest version
  pod 'SwiftyJSON', :git => "https://github.com/SwiftyJSON/SwiftyJSON.git"

  target 'SocketTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SocketTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
